version: '3.8'

services:
  php:
    build: ./php
    container_name: webb_php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - webb_net

  mysql:
    image: mysql:8.0
    container_name: webb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: webb_db
      MYSQL_USER: webb_user
      MYSQL_PASSWORD: webb_pass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - webb_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webb_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webb_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root1234
    depends_on:
      - mysql
    networks:
      - webb_net

volumes:
  webb_mysql_data:

networks:
  webb_net:
    driver: bridge
